switch.theater_candy_lights_switch_25_0:
  polling_intensity: 1
switch.master_ac_switch_17_0:
  polling_intensity: 1
light.driveway_lights_level_4_0:
  polling_intensity: 1
light.boiler_room_lights_level_2_0:
  polling_intensity: 1
light.front_door_lights_level_5_0:
  polling_intensity: 1
light.dinning_room_lights_level_6_0:
  polling_intensity: 1
light.stair_lights_level_7_0:
  polling_intensity: 1
light.living_room_lights_level_9_0:
  polling_intensity: 1
light.laundry_lights_level_11_0:
  polling_intensity: 1
light.master_entrance_lights_level_12_0:
  polling_intensity: 1
light.master_bedroom_lights_level_16_0:
  polling_intensity: 1
light.sunroom_treadmill_lights_level_18_0:
  polling_intensity: 1
light.master_wall_lights_level_19_0:
  polling_intensity: 1
light.pool_lights_level_20_0:
  polling_intensity: 1
switch.theater_posters_switch_22_0:
  polling_intensity: 1
light.theater_lights_level_23_0:
  polling_intensity: 1
light.playroom_lights_level_21_0:
  polling_intensity: 1
light.isabellas_room_lights_level_29_0:
  polling_intensity: 1
light.upstairs_hallway_lights_level_30_0:
  polling_intensity: 1
light.mudroom_hallway_lights_level_31_0:
  polling_intensity: 1
light.attic_lights_level_33_0:
  polling_intensity: 1
light.mudroom_entrance_lights_level_35_0:
  polling_intensity: 1
light.downstairs_bathroom_lights_level_36_0:
  polling_intensity: 1
light.office_lights_level_37_0:
  polling_intensity: 1
light.living_room_fan_level_10_0:
  polling_intensity: 1
light.master_entrance_fan_level_13_0:
  polling_intensity: 1
light.master_bedroom_fan_level_15_0:
  polling_intensity: 1
switch.downstairs_bathroom_fan_switch_34_0:
  polling_intensity: 1
