# FRONT DOOR PACKAGE
# Front door open/close sensor and future door lock
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    sensor.front_door:
      icon: mdi:glassdoor
      friendly_name: Front Door

    # Hide raw sensor
    binary_sensor.front_door_sensor_sensor_42_0:
      hidden: true

sensor:
#----------------------------------------------------------------
  - platform: template
    sensors:
      front_door:
        friendly_name: 'Front Door'
        value_template: >-
          {% if states.binary_sensor.front_door_sensor_sensor_42_0.state %}
            {% if is_state('binary_sensor.front_door_sensor_sensor_42_0', 'off') %}
              Closed
            {% else %}
              Opened
            {% endif %}
          {% else %}
            Unknown
          {% endif %}

automation:
#----------------------------------------------------------------
  - alias: NOTIFY (OPEN 10 MIN) Front Door
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_sensor_sensor_42_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.options_notifications_push
        state: 'on'

    action:
    - service: notify.pushetta_carinajesse
      data:
        message: "Front Door Open For 10 Min!"
        title: ""
