# LIGHT PACKAGE
#----------------------------------------------------------------

sensor:
#----------------------------------------------------------------
  - platform: template
    sensors:
      lights_on:
        friendly_name: 'Lights On'
        value_template: >-
          {{ states.light|selectattr("state", "equalto", "on")|list|length }}

homeassistant:
  customize:
  #----------------------------------------------------------------

    sensor.lights:
      icon: mdi:lightbulb-on-outline
      friendly_name: Lights On

    light.driveway_lights_level_4_0:
      icon: mdi:car
      entity_picture:
      friendly_name: Driveway Light

    light.boiler_room_lights_level_2_0:
      icon: mdi:opacity
      entity_picture:
      friendly_name: Boiler Room Light

    light.front_door_lights_level_5_0:
      icon: mdi:home
      entity_picture:
      friendly_name: Front Door Light

    light.dinning_room_lights_level_6_0:
      icon: mdi:silverware
      entity_picture:
      friendly_name: Dinning Room Light

    light.stair_lights_level_7_0:
      icon: mdi:stairs
      entity_picture:
      friendly_name: Stair Light

    light.living_room_lights_level_9_0:
      icon: mdi:sofa
      entity_picture:
      friendly_name: Living Room Light

    light.laundry_lights_level_11_0:
      icon: mdi:beaker
      entity_picture:
      friendly_name: Laundry Light

    light.master_entrance_lights_level_12_0:
      icon: mdi:glassdoor
      entity_picture:
      friendly_name: Master Entrance Light

    light.master_bedroom_lights_level_16_0:
      icon: mdi:hotel
      entity_picture:
      friendly_name: Master Bedroom Light

    light.sunroom_treadmill_lights_level_18_0:
      icon: mdi:transit-transfer
      entity_picture:
      friendly_name: Sunroom Treadmill Light

    light.master_wall_lights_level_19_0:
      icon: mdi:glasses
      entity_picture:
      friendly_name: Master Wall Light

    light.pool_lights_level_20_0:
      icon: mdi:pool
      entity_picture:
      friendly_name: Pool Light

    switch.theater_posters_switch_22_0:
      icon: mdi:account-box-outline
      entity_picture:
      friendly_name: Theater Posters

    light.theater_lights_level_23_0:
      icon: mdi:theater
      entity_picture:
      friendly_name: Theater Light

    switch.theater_candy_lights_switch_25_0:
      icon: mdi:candycane
      entity_picture:
      friendly_name: Theater Candy Light

    light.playroom_lights_level_21_0:
      icon: mdi:duck
      entity_picture:
      friendly_name: Playroom Light

    light.isabellas_room_light_level_29_0:
      icon: mdi:baby-buggy
      entity_picture:
      friendly_name: Isabella's Room Light

    light.upstairs_hallway_lights_level_30_0:
      icon: mdi:arrange-send-to-back
      entity_picture:
      friendly_name: Upstairs Hallway Light

    light.mudroom_hallway_lights_level_31_0:
      icon: mdi:blur-radial
      entity_picture:
      friendly_name: Mudroom Hallway Light

    light.attic_lights_level_33_0:
      icon: mdi:publish
      entity_picture:
      friendly_name: Attic Light

    light.mudroom_entrance_lights_level_35_0:
      icon: mdi:blur-linear
      entity_picture:
      friendly_name: Mudroom Entrance Light

    light.downstairs_bathroom_lights_level_36_0:
      icon: mdi:baby
      entity_picture:
      friendly_name: Downstairs Bathroom Light

    light.office_lights_level_37_0:
      icon: mdi:guitar-electric
      entity_picture:
      friendly_name: Office Light

group:
#----------------------------------------------------------------

  # ALL
  #----------------------------------------------------------------
  lights_all:
    name: All Lights
    view: no
    icon: mdi:lightbulb
    entities:
    - group.lights_all_outside
    - group.lights_all_upstairs
    - group.lights_all_downstairs

  # OUTSIDE
  #----------------------------------------------------------------
  lights_all_outside:
    name: All Outside Lights
    view: no
    icon: mdi:lightbulb
    entities:
    - group.lights_outside

  lights_outside:
    name: Outside
    view: no
    icon: mdi:lightbulb
    entities:
    - light.driveway_lights_level_4_0
    - light.front_door_lights_level_5_0
    - light.pool_lights_level_20_0

  # UPSTAIRS
  #----------------------------------------------------------------
  lights_all_upstairs:
    name: All Upstairs Lights
    view: no
    icon: mdi:lightbulb
    entities:
    - group.lights_master_bedroom
    - group.lights_living_room
    - group.lights_upstairs

  lights_master_bedroom:
    name: Master Bedroom
    view: no
    icon: mdi:lightbulb
    entities:
    - light.master_entrance_lights_level_12_0
    - light.master_entrance_fan_level_13_0
    - light.master_bedroom_lights_level_16_0
    - light.master_bedroom_fan_level_15_0
    - light.master_wall_lights_level_19_0
    - switch.master_ac_switch_17_0

  lights_living_room:
    name: Living Room
    view: no
    icon: mdi:lightbulb
    entities:
    - light.living_room_lights_level_9_0
    - light.living_room_fan_level_10_0

  lights_upstairs:
    name: Upstairs
    view: no
    icon: mdi:lightbulb
    entities:
    - light.dinning_room_lights_level_6_0
    - light.stair_lights_level_7_0
    - light.laundry_lights_level_11_0
    - light.sunroom_treadmill_lights_level_18_0
    - light.isabellas_room_light_level_29_0
    - light.upstairs_hallway_lights_level_30_0
    - light.attic_lights_level_33_0

  # DOWNSTAIRS
  #----------------------------------------------------------------
  lights_all_downstairs:
    name: All Upstairs Lights
    view: no
    icon: mdi:lightbulb
    entities:
    - group.lights_garage
    - group.lights_mudroom
    - group.lights_downstairs_bathroom
    - group.lights_downstairs
    - group.lights_theater

  lights_garage:
    name: Garage
    view: no
    icon: mdi:lightbulb
    entities:
    - light.boiler_room_lights_level_2_0

  lights_mudroom:
    name: Mudroom
    view: no
    icon: mdi:lightbulb
    entities:
    - light.mudroom_hallway_lights_level_31_0
    - light.mudroom_entrance_lights_level_35_0

  lights_downstairs_bathroom:
    name: Downstairs Bathroom
    view: no
    icon: mdi:lightbulb
    entities:
    - light.downstairs_bathroom_lights_level_36_0
    - switch.downstairs_bathroom_fan_switch_34_0

  lights_downstairs:
    name: Downstairs
    view: no
    icon: mdi:lightbulb
    entities:
    - light.playroom_lights_level_21_0
    - light.office_lights_level_37_0

  lights_theater:
    name: Theater
    view: no
    icon: mdi:lightbulb
    entities:
    - switch.theater_posters_switch_22_0
    - light.theater_lights_level_23_0
    - switch.theater_candy_lights_switch_25_0

automation:
#----------------------------------------------------------------

  - alias: Turn on the front door light at sunset
    trigger:
      platform: sun
      event: sunset
      offset: '-00:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_on
        state: 'on'
    action:
     service: light.turn_on
     entity_id: light.front_door_lights_level_5_0

  - alias: 'Turn off front lights @ 11PM'
    trigger:
      platform: time
      after: '23:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      service: light.turn_off
      entity_id: light.front_door_lights_level_5_0

  - alias: 'Turn off outdoor lights during the day'
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      service: homeassistant.turn_off
      entity_id: group.lights_outside

  - alias: Turn On Living Room Scenes
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.living_room_scenes
    action:
      service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.living_room_scenes", "Off") %}
            scene.living_room_off
          {%-elif is_state("input_select.living_room_scenes", "See") %}
            scene.living_room_see
          {%-elif is_state("input_select.living_room_scenes", "Read") %}
            scene.living_room_read
          {%-elif is_state("input_select.living_room_scenes", "Relax") %}
            scene.living_room_relax
          {%-elif is_state("input_select.living_room_scenes", "Sleep") %}
            scene.living_room_sleep
          {%-elif is_state("input_select.living_room_scenes", "Cool") %}
            scene.living_room_cool
          {%-elif is_state("input_select.living_room_scenes", "Fan Off") %}
            scene.living_room_fan_off
          {% else %}
            none
          {% endif %}

  - alias: Turn On Theater Scenes
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.theater_scenes
    action:
      service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.theater_scenes", "Off") %}
            scene.theater_off
          {%-elif is_state("input_select.theater_scenes", "See") %}
            scene.theater_see
          {%-elif is_state("input_select.theater_scenes", "Read") %}
            scene.theater_read
          {%-elif is_state("input_select.theater_scenes", "Relax") %}
            scene.theater_relax
          {%-elif is_state("input_select.theater_scenes", "Sleep") %}
            scene.theater_sleep
          {% else %}
            none
          {% endif %}

  - alias: School Day Turn on lights weekday 6AM

    trigger:
      - platform: time
        after: '06:00'

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_on
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: scene.turn_on
        entity_id: scene.school_morning_on

  - alias: School Day Turn off lights weekday 8:20AM
    trigger:
      - platform: time
        after: '08:20'
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_on
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: scene.turn_on
        entity_id: scene.school_morning_off

  # Turn off downstairs bathroom lights after 15 minutes
  - alias: "Turn off downstairs bathroom lights after 20 minutes"

    trigger:
      - platform: state
        entity_id: light.downstairs_bathroom_lights_level_36_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 20
          seconds: 0

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'

    action:
      - service: scene.turn_on
        entity_id: scene.downstairs_bathroom_off

  # Turn off attic light after 15 minutes
  - alias: "Turn off attic lights after 30 minutes"

    trigger:
      - platform: state
        entity_id: light.attic_lights_level_33_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 30
          seconds: 0

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.attic_lights_level_33_0

  # Turn off theater poster after 15 minutes
  - alias: "Turn off theater poster lights after 15 minutes"

    trigger:
      - platform: state
        entity_id: switch.theater_posters_switch_22_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.theater_posters_switch_22_0

  # Turn off theater candy light after 15 minutes
  - alias: "Turn off theater candy light after 15 minutes"

    trigger:
      - platform: state
        entity_id: switch.theater_candy_lights_switch_25_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'

    action:
      - service: switch.turn_off
        entity_id: switch.theater_candy_lights_switch_25_0


  # Turn off theater light after 15 minutes
  - alias: "Turn off theater light after 15 minutes"

    trigger:
      - platform: state
        entity_id: light.theater_lights_level_23_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.theater_lights_level_23_0

  # Turn off boiler room light after 15 minutes
  - alias: "Turn off boiler room lights after 15 minutes"

    trigger:
      - platform: state
        entity_id: light.boiler_room_lights_level_2_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0

    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.boiler_room_lights_level_2_0
