# THEATER LIGHTS
# Automations with theater lighting
#----------------------------------------------------------------

script:
#----------------------------------------------------------------
  # Use this whenever turning off theater lights through automation
  # Avoids false positive camera motion when lights turn off
  auto_off_theater_light:
    sequence:
      - service: automation.turn_off
        entity_id: automation.auto_motion_theater_light
      - service: light.turn_off
        entity_id: light.theater_lights_level_23_0
      - delay: 00:00:15
      - service: sensor.turn_off
        entity_id: sensor.motion_indoor_camera_theater
      - service: automation.turn_on
        entity_id: automation.auto_motion_theater_light

automation:
#----------------------------------------------------------------

  # Motion activated
  #----------------------------------------------------------------
  # Smart, motion activated theater light (on and off)
  - alias: AUTO (Motion) Theater Light
    trigger:
      # Triggers to turn on light as soon as there is motion
      - platform: state
        entity_id: sensor.motion_indoor_camera_theater
        to: 'On'
      # Triggers to turn off light when there has been no motion for 90 seconds
      - platform: state
        entity_id: sensor.motion_indoor_camera_theater
        to: 'Off'
        for:
          minutes: 1
          seconds: 30
    # Only if not watching TV or playing a game
    condition:
      - condition: template
        value_template: '{{ states.remote.harmonyhubtheater.attributes.current_activity == "PowerOff" }}'
    action:
      # Only if auto lights option is on
      service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if trigger.to_state.state == "On" and states.input_boolean.options_lights_auto_on.state == "on" %}
            light.theater_lights_level_23_0
          {% elif trigger.to_state.state == "Off" and states.input_boolean.options_lights_auto_off.state == "on"  %}
            script.auto_off_theater_light
          {% endif %}

  # Turn off non motion activated theater lights after 15 minutes
  # And there is no motion
  - alias: AUTO OFF (SAVER) Theater Lights
    trigger:
      - platform: state
        entity_id:
          - switch.theater_posters_switch_22_0
          - switch.theater_candy_lights_switch_25_0
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
      # Triggers to turn off light when there has been no motion for 90 seconds
      - condition: state
        entity_id: sensor.motion_indoor_camera_theater
        state: 'Off'
        for:
          minutes: 15
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.event.data.entity_id }}"
