# RESIDENTS PACKAGE
# Notifies and performs automations when key residents arrive
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    sensor.tracker_jesse:
      icon: mdi:cellphone-iphone
      entity_picture: /local/pictures/jesse.png
      friendly_name: Jesse

    sensor.tracker_carina:
      icon: mdi:cellphone-iphone
      entity_picture: /local/pictures/carina.png
      friendly_name: Carina

    sensor.tracker_bianca:
      icon: mdi:cellphone-iphone
      entity_picture: /local/pictures/bianca.png
      friendly_name: Bianca

    sensor.tracker_ryan:
      icon: mdi:cellphone-iphone
      entity_picture: /local/pictures/ryan.png
      friendly_name: Ryan

group:
#----------------------------------------------------------------

  residents_all:
    name: Residents
    view: no
    icon: mdi:account-multiple
    entities:
    - sensor.tracker_jesse
    - sensor.tracker_carina
    - sensor.tracker_bianca
    - sensor.tracker_ryan

sensor:
#----------------------------------------------------------------

  # Every resident is "sensed" through device tracking of their phones.
  # Here I prioritize "sensing" their device connected to my home network
  # over what iCloud indicates
  #----------------------------------------------------------------
  - platform: template
    sensors:
      tracker_jesse:
        friendly_name: 'Jesse'
        value_template: >-
          {% if is_state('device_tracker.phonejesse', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

  - platform: template
    sensors:
      tracker_carina:
        friendly_name: 'Carina'
        value_template: >-
          {% if is_state('device_tracker.phonecarina', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

  - platform: template
    sensors:
      tracker_bianca:
        friendly_name: 'Bianca'
        value_template: >-
          {% if is_state('device_tracker.phonebianca', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

  - platform: template
    sensors:
      tracker_ryan:
        friendly_name: 'Ryan'
        value_template: >-
          {% if is_state('device_tracker.phoneryan', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

automation:
#----------------------------------------------------------------

  # NOTIFICATIONS
  #----------------------------------------------------------------

  # Send a notification when key residents arrive
  - alias: NOTIFY (HOME) Resident
    initial_state: False # start disabled to avoid false positives on HA restart  
    hide_entity: True
    trigger:
      - platform: state
        entity_id:
          - sensor.tracker_jesse
          - sensor.tracker_carina
          - sensor.tracker_bianca
          - sensor.tracker_ryan
        to: 'Home'
    condition:
      - condition: state
        entity_id: input_boolean.options_notifications_push
        state: 'on'
    action:
      - service: notify.pushetta_carinajesse
        data_template:
          message: "{{ trigger.entity_id.split('.')[1].lower().replace('tracker_', '').title() }} is home"
          title: ""
