# VIDEO PLAYER PACKAGE
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    media_player.living_room_apple_tv:
      icon: mdi:plex
      friendly_name: Living Room (Apple TV)

    media_player.jesses_iphone_7_plus:
      icon: mdi:plex
      friendly_name: Jesse (iPhone)

    media_player.shield_android_tv:
      icon: mdi:plex
      friendly_name: Theater (Shield)

    media_player.plex_for_tivo_tivo_tcda92000:
      icon: mdi:plex
      friendly_name: Tivo Mini

    media_player.roku_3__4e757u072189:
      icon: mdi:plex
      friendly_name: Bogar (House)

sensor:
#----------------------------------------------------------------

  # Modified component to:
  # 1) Show player name if username is blank
  # 2) Show TV show, season, and episode number
  - platform: plexactivitymonitor
    host: !secret plex_server_host
    port: !secret plex_server_port
    username: !secret plex_server_username
    password: !secret plex_server_password

media_player:
#----------------------------------------------------------------

  - platform: plex
    include_non_clients: true
    use_episode_art: true
    use_dynamic_groups: true  
