# VIDEO PLAYER PACKAGE
#----------------------------------------------------------------

homeassistant:
  customize:
  #----------------------------------------------------------------

    media_player.plex_dy4hdna2drhn:
      icon: mdi:plex
      friendly_name: Living Room (Apple TV)

    media_player.plex_c0kfc142ddr5:
      icon: mdi:plex
      friendly_name: Kitchen (Apple TV)

    media_player.plex_7b8c4c63_38ff_417d_ac14_0457796ee1c1:
      icon: mdi:plex
      friendly_name: Jesse (iPhone)

    media_player.plex_bb72ed6a42aa26ea_com_plexapp_android:
      icon: mdi:plex
      friendly_name: Theater (Shield)

    # TiVo TCD848000
    media_player.plex_mwmj7d2er7m34n29:
      icon: mdi:plex
      friendly_name: Theater (Tivo)

    media_player.plex_e0jqqsjh1g1:
      icon: mdi:plex
      friendly_name: Living Room (Tivo)

    media_player.plex_wkx1npeb5oe:
      icon: mdi:plex
      friendly_name: Master Bedroom (Tivo)

    media_player.plex_c0hjm0x4drhn:
      icon: mdi:plex
      friendly_name: Master Bedroom (Apple TV)

    #media_player.roku_3__4e757u072189:
    media_player.plex_a71ac5a0652e6d9bfc21f7da5b03f1ca:
      icon: mdi:plex
      friendly_name: Bogar (House)

sensor:
#----------------------------------------------------------------

  # Modified component to:
  # 1) Show player name if username is blank
  # 2) Show TV show, season, and episode number
  - platform: plexactivitymonitor
    host: !secret plex_server_host
    port: !secret plex_server_port
    username: !secret plex_server_username
    password: !secret plex_server_password

media_player:
#----------------------------------------------------------------

  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    use_episode_art: true
    use_dynamic_groups: true
    use_custom_entity_ids: true
    show_all_controls: false
    scan_interval: 5
    max_frozen_playing: 15
    max_frozen_paused: 30
