# VIDEO PLAYER PACKAGE
#----------------------------------------------------------------

sensor:
#----------------------------------------------------------------

  # Modified component to:
  # 1) Show player name if username is blank
  # 2) Show TV show, season, and episode number
  - platform: plexactivitymonitor
    host: !secret plex_server_host
    port: !secret plex_server_port
    username: !secret plex_server_username
    password: !secret plex_server_password


media_player:
#----------------------------------------------------------------

  - platform: plex
    name: plex_server
    ip_address: !secret plex_server_host
    port: !secret plex_server_port
    token: !secret plex_server_token
