# ZWAVE
#----------------------------------------------------------------

# TO START THE OCW CONTROL PANEL
# 1. Stop HA
# 2. cd /srv/hass/src/open-zwave-control-panel/
# 3. sudo ./ozwcp -p 8888
# 4. USE /dev/ttyUSB-ZStick-5G

# Setting up Z-Wave switches:
# 1. Ensure devices is recognized (should display as light.__level_#)
# 2. Restart HA
# 3. Should display as light.your_brand_level_#
# 4. Call HA servuce "zwave/rename_node" - set service data as:
#     {
#       "entity_id": "light.your_brand_level_#",
#       "name": "Your New Name"
#     }
# 5. Restart HA
# 6. Should display as light.your_new_name_level_#

# ZWAVE - AEOTEC MULTISENSOR (set motion sensor On duration to just over 2 minutes. (shorter and it never registers as on!))
#----------------------------------------------------------------
# services | zwave | set_config_parameter
# {
#     "node_id": 24,
#     "parameter": 3,
#     "value": 125
# }

# ZWAVE - AEOTEC MULTISENSOR (set the temperature sensor interval to 120 seconds)
#----------------------------------------------------------------
# services | zwave | set_config_parameter
# {
#     "node_id": 24,
#     "parameter": 111,
#     "value": 120
# }

# ZWAVE - AEOTEC DOOR SENSOR (send both Sensor Binary Reports and Basic Reports)
#----------------------------------------------------------------
# services | zwave | set_config_parameter
# {
#     "node_id": 40,
#     "parameter": 121,
#     "value": 272
# }

# ZWAVE - NODE RENAME
#----------------------------------------------------------------
# services | zwave | rename_node
# {
#     "entity_id": "binary_sensor.__sensor_40_0",
#     "name": "Mudroom Door Sensor"
# }

# TO GIVE THE USB STICK A CONSISTENT NAME
#----------------------------------------------------------------
# https://www.domoticz.com/wiki/PersistentUSBDevices
# Run ls /dev/ttyACM* to find your USB path
# For the AeoTec Z-Stick Gen5:
# sudo nano /etc/udev/rules.d/99-usb-serial.rules and add the following:
#   SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="ttyUSB-ZStick-5G"
# Your USB path is now /dev/ttyUSB-ZStick-5G

automation:
#----------------------------------------------------------------

  - alias: HEAL (NIGHTLY) Z-Wave
    hide_entity: True
    trigger:
      platform: time
      after: '4:00:00'
    action:
      service: zwave.heal_network
