# ZWAVE
#----------------------------------------------------------------

# TO START THE OCW CONTROL PANEL
# 1. Stop HA
# 2. cd /srv/hass/src/open-zwave-control-panel/
# 3. sudo ./ozwcp -p 8888
# 4. USE /dev/ttyUSB-ZStick-5G

# Setting up Z-Wave switches:
# 1. Ensure devices is recognized (should display as light.__level_#)
# 2. Restart HA
# 3. Should display as light.your_brand_level_#
# 4. Call HA servuce "zwave/rename_node" - set service data as:
#     {
#       "entity_id": "light.your_brand_level_#",
#       "name": "Your New Name"
#     }
# 5. Restart HA
# 6. Should display as light.your_new_name_level_#

# ZWAVE - AEOTEC MULTISENSOR (set motion sensor On duration to just over 2 minutes. (shorter and it never registers as on!))
#----------------------------------------------------------------
# services | zwave | set_config_parameter
# {
#     "node_id": 24,
#     "parameter": 3,
#     "value": 125
# }

# ZWAVE - AEOTEC MULTISENSOR (set the temperature sensor interval to 120 seconds)
#----------------------------------------------------------------
# services | zwave | set_config_parameter
# {
#     "node_id": 24,
#     "parameter": 111,
#     "value": 120
# }

# ZWAVE - AEOTEC DOOR SENSOR (send both Sensor Binary Reports and Basic Reports)
#----------------------------------------------------------------
# services | zwave | set_config_parameter
# {
#     "node_id": 40,
#     "parameter": 121,
#     "value": 272
# }

# ZWAVE - NODE RENAME
#----------------------------------------------------------------
# services | zwave | rename_node
# {
#     "entity_id": "binary_sensor.__sensor_40_0",
#     "name": "Mudroom Door Sensor"
# }

# TO GIVE THE USB STICK A CONSISTENT NAME
#----------------------------------------------------------------
# https://www.domoticz.com/wiki/PersistentUSBDevices
# Run ls /dev/ttyACM* to find your USB path
# For the AeoTec Z-Stick Gen5:
# sudo nano /etc/udev/rules.d/99-usb-serial.rules and add the following:
#   SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="ttyUSB-ZStick-5G"
# Your USB path is now /dev/ttyUSB-ZStick-5G

zwave:
#----------------------------------------------------------------

  usb_path: /dev/ttyUSB-ZStick-5G
  polling_interval: 2000
  autoheal: true
  config_path: /srv/hass/src/python-openzwave/openzwave/config
  customize: # This attribute contains node-specific override values:
    switch.theater_candy_lights_switch_25_0:
      polling_intensity: 1 #Enables polling of a value and sets the frequency of polling (0=none, 1=every time through the list, 2=every other time, etc). If not specified then your device will not be polled.
    switch.master_ac_switch_17_0:
      polling_intensity: 1
    light.driveway_lights_level_4_0:
      polling_intensity: 1
    light.boiler_room_lights_level_2_0:
      polling_intensity: 1
    light.front_door_lights_level_5_0:
      polling_intensity: 1
    light.dinning_room_lights_level_6_0:
      polling_intensity: 1
    light.stair_lights_level_7_0:
      polling_intensity: 1
    light.living_room_lights_level_9_0:
      polling_intensity: 1
    light.laundry_lights_level_11_0:
      polling_intensity: 1
    light.master_entrance_lights_level_12_0:
      polling_intensity: 1
    light.master_bedroom_lights_level_16_0:
      polling_intensity: 1
    light.sunroom_treadmill_lights_level_18_0:
      polling_intensity: 1
    light.master_wall_lights_level_19_0:
      polling_intensity: 1
    light.pool_lights_level_20_0:
      polling_intensity: 1
    switch.theater_posters_switch_22_0:
      polling_intensity: 1
    light.theater_lights_level_23_0:
      polling_intensity: 1
    light.playroom_lights_level_21_0:
      polling_intensity: 1
    light.isabellas_room_lights_level_29_0:
      polling_intensity: 1
    light.upstairs_hallway_lights_level_30_0:
      polling_intensity: 1
    light.mudroom_hallway_lights_level_31_0:
      polling_intensity: 1
    light.attic_lights_level_33_0:
      polling_intensity: 1
    light.mudroom_entrance_lights_level_35_0:
      polling_intensity: 1
    light.downstairs_bathroom_lights_level_36_0:
      polling_intensity: 1
    light.office_lights_level_37_0:
      polling_intensity: 1
    light.living_room_fan_level_10_0:
      polling_intensity: 1
    light.master_entrance_fan_level_13_0:
      polling_intensity: 1
    light.master_bedroom_fan_level_15_0:
      polling_intensity: 1
    switch.downstairs_bathroom_fan_switch_34_0:
      polling_intensity: 1

automation:
#----------------------------------------------------------------

  - alias: HEAL (NIGHTLY) Z-Wave
    hide_entity: True
    trigger:
      platform: time
      after: '4:00:00'
    action:
      service: zwave.heal_network
